CREATE DATABASE submissions

CREATE TABLE IF NOT EXISTS  shipments(
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    date DATE NOT NULL DEFAULT NOW(),
    carrier_id INTEGER REFERENCES carriers(id),
    origin_country TEXT NOT NULL,
    origin_state TEXT NOT NULL,
    origin_city TEXT NOT NULL,
    destination_country TEXT NOT NULL,
    destination_state TEXT NOT NULL,
    destination_city TEXT NOT NULL,
    pickup_date DATE NULL,
    delivery_date DATE NULL,
    status TEXT,
    carrier_rate FLOAT
);

CREATE TABLE IF NOT EXISTS carriers(
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name TEXT NOT NULL CHECK(name <> ''),
    scac TEXT NOT NULL CHECK(scac <> ''),
    mc INTEGER,
    dot INTEGER,
    fein TEXT
);

CREATE TABLE IF NOT EXISTS orders(
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    carrier_id INTEGER REFERENCES carriers(id),
    provider TEXT NOT NULL,
    address TEXT NOT NULL,
    phone TEXT,
    description_order TEXT,
    quantity INTEGER NOT NULL,
    unit_price INTEGER NOT NULL,
    total_price INTEGER,
    delivery_date DATE NOT NULL
);